package:
  name: transcv
  version: 0.0.3
source:
  sha256: 4e33ca072a0d6dd5ff9e70b58a526f0f8698e6c3435b3e9885eaa6a022be5840
  url: https://files.pythonhosted.org/packages/a5/bd/14a487fcbfd7c442541f52d4bb78cb3dcc580cde09cea110d6c97ca802ec/transcv-0.0.3.tar.gz
about:
  dev_url: https://Ys-Prakash.github.io
  doc_url: https://Ys-Prakash.github.io
  home: https://Ys-Prakash.github.io
  license: Apache Software
  license_family: APACHE
  summary: A library for creating vision transformers for computer vision
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - Ys-Prakash
requirements:
  host:
  - pip
  - python
  - packaging
  - fastai
  - timm
  - transformers[sentencepiece]
  run:
  - pip
  - python
  - packaging
  - fastai
  - timm
  - transformers[sentencepiece]
test:
  imports:
  - transcv
