package:
  name: transcv
  version: 0.0.2
source:
  sha256: 6a5015c2db9122dddef0d347dfb5e879ad85d8563b52bf855244fb1dbcc39621
  url: https://files.pythonhosted.org/packages/5c/fa/2e90dd5346e01b2dc6a3f0ef6ac8767a284a8749fde5bc45789af6b122a2/transcv-0.0.2.tar.gz
about:
  dev_url: https://Ys-Prakash.github.io
  doc_url: https://Ys-Prakash.github.io
  home: https://Ys-Prakash.github.io
  license: Apache Software
  license_family: APACHE
  summary: A library for creating vision transformers for computer vision
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - Ys-Prakash
requirements:
  host:
  - pip
  - python
  - packaging
  - fastai
  - timm
  - transformers[sentencepiece]
  run:
  - pip
  - python
  - packaging
  - fastai
  - timm
  - transformers[sentencepiece]
test:
  imports:
  - transcv
