package:
  name: transcv
  version: 0.0.5
source:
  sha256: 40cc934a65c56edb6b1adc2bc4bad5500109f515a7d43bd81d15d910769f764c
  url: https://files.pythonhosted.org/packages/32/9e/048c019951d7f5c5cca1a5cf16a4781b64aee912e0cae006746e9ad4999c/transcv-0.0.5.tar.gz
about:
  dev_url: https://Ys-Prakash.github.io
  doc_url: https://Ys-Prakash.github.io
  home: https://Ys-Prakash.github.io
  license: Apache Software
  license_family: APACHE
  summary: A library for creating vision transformers for computer vision
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - Ys-Prakash
requirements:
  host:
  - pip
  - python
  - packaging
  - fastai
  - timm
  - transformers[sentencepiece]
  run:
  - pip
  - python
  - packaging
  - fastai
  - timm
  - transformers[sentencepiece]
test:
  imports:
  - transcv
