package:
  name: transcv
  version: 0.0.4
source:
  sha256: 494e91e360c404494f2db0999d50c6ac32f3b009c2a3db342157da3624b403c6
  url: https://files.pythonhosted.org/packages/ce/b8/5c425d8040d31d5d194387285c62b82813c39fca45fc5e77909b495db839/transcv-0.0.4.tar.gz
about:
  dev_url: https://Ys-Prakash.github.io
  doc_url: https://Ys-Prakash.github.io
  home: https://Ys-Prakash.github.io
  license: Apache Software
  license_family: APACHE
  summary: A library for creating vision transformers for computer vision
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - Ys-Prakash
requirements:
  host:
  - pip
  - python
  - packaging
  - fastai
  - timm
  - transformers[sentencepiece]
  run:
  - pip
  - python
  - packaging
  - fastai
  - timm
  - transformers[sentencepiece]
test:
  imports:
  - transcv
